# Generated by Django 5.2.3 on 2025-06-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_notificatrion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificatrion',
            new_name='Notification',
        ),
    ]
